In [1]:
from lab2 import *
train, dev, X_test = load_datasets_unlabeled_test()

In [2]:
X_train, y_train = train
X_dev, y_dev = dev
len(X_train), len(X_dev), len(X_test)

(963, 107, 500)

## 2. Entrenar

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC, SVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from tagging.fasttext2 import FasttextDictVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from util import print_short_eval
from sklearn.feature_extraction.text import TfidfVectorizer



#probando distintos clasificadores
clfs = [
    KNeighborsClassifier(),
    MultinomialNB(),
    DecisionTreeClassifier(random_state=0),
    LogisticRegression(random_state=0),
    LinearSVC(random_state=0),
    SVC(random_state=0),
    RandomForestClassifier(random_state=0),
]

#probar vectorizadores
vect = TfidfVectorizer(binary=True) #solo mejora el logistic regression
#vect = CountVectorizer(binary=True)

for clf in clfs:
    print(str(clf.__class__))
    pipeline = Pipeline([
        ('vect', vect),
        ('clf', clf),
    ])
    pipeline.fit(X_train, y_train)
    print_short_eval(pipeline, X_train, y_train)
    print_short_eval(pipeline, X_dev, y_dev)

<class 'sklearn.neighbors.classification.KNeighborsClassifier'>
accuracy	0.86	macro f1	0.86
accuracy	0.83	macro f1	0.83
<class 'sklearn.naive_bayes.MultinomialNB'>
accuracy	0.99	macro f1	0.99
accuracy	0.84	macro f1	0.84
<class 'sklearn.tree.tree.DecisionTreeClassifier'>
accuracy	1.00	macro f1	1.00
accuracy	0.70	macro f1	0.70
<class 'sklearn.linear_model.logistic.LogisticRegression'>


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


accuracy	0.99	macro f1	0.99
accuracy	0.88	macro f1	0.88
<class 'sklearn.svm.classes.LinearSVC'>
accuracy	1.00	macro f1	1.00
accuracy	0.87	macro f1	0.87
<class 'sklearn.svm.classes.SVC'>


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


accuracy	0.50	macro f1	0.33
accuracy	0.50	macro f1	0.33
<class 'sklearn.ensemble.forest.RandomForestClassifier'>


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


accuracy	0.99	macro f1	0.99
accuracy	0.75	macro f1	0.74


In [5]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from util import print_eval

pipeline = Pipeline([
    ('vect', CountVectorizer(
        binary=True,
        min_df=5,
        max_df=0.95,
        ngram_range=(1, 3),
        #stop_words='english',
    )),
    ('clf', LogisticRegression(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.91

              precision    recall  f1-score   support

         neg       0.88      0.94      0.91        54
         pos       0.94      0.87      0.90        53

    accuracy                           0.91       107
   macro avg       0.91      0.91      0.91       107
weighted avg       0.91      0.91      0.91       107

[[51  3]
 [ 7 46]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [50]:
#grid search
from sklearn.model_selection import ParameterGrid

param_grid = {
    'vect__binary': [True],
    #'vect__ngram_range': [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5)],
    #'vect__min_df': [1, 3, 5, 7],
    #'vect__max_df': [0.95, 0.9, 0.7],
    #segunda vuelta
    'vect__ngram_range': [(1, 3)],
    'vect__min_df': [ 5],
    'vect__max_df': [0.95],

    #mismos resultados
    'clf__alpha': [1.0,5.0,10.0,11.5,11.8,11.9,11.95,12.0,12.05,12.1,12.3,12.4]
    #'clf__alpha': [10.0,11.0,12.0,13.0]
}

params_list = list(ParameterGrid(param_grid))

In [54]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from util import print_eval
from sklearn.feature_extraction.text import TfidfVectorizer


pipeline = Pipeline([
    ('vect', CountVectorizer(
        binary=True,
        min_df=5,
        max_df=0.95,
        ngram_range=(1, 3),
        #stop_words='english',
    )),
    ('clf', MultinomialNB(alpha=12.0,fit_prior=True)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.89

              precision    recall  f1-score   support

         neg       0.92      0.85      0.88        54
         pos       0.86      0.92      0.89        53

    accuracy                           0.89       107
   macro avg       0.89      0.89      0.89       107
weighted avg       0.89      0.89      0.89       107

[[46  8]
 [ 4 49]]


In [51]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn import metrics
from util import eval

pipeline = Pipeline([
    ('vect', CountVectorizer()),
    ('clf', MultinomialNB()),
])

results = []
for params in params_list:
    # TODO: add progress bar!
    pipeline.set_params(**params)
    pipeline.fit(X_train, y_train)
    result = eval(pipeline, X_dev, y_dev)
    
    results.append({
        **result,
        **params,
    })

In [52]:
import pandas as pd

results_df = pd.DataFrame(results)
results_df.sort_values(['acc', 'f1'], ascending=False)[:10]

acc  clf__alpha        f1  vect__binary  vect__max_df  vect__min_df  \
4   0.887850       11.80  0.887762          True          0.95             5   
5   0.887850       11.90  0.887762          True          0.95             5   
6   0.887850       11.95  0.887762          True          0.95             5   
7   0.887850       12.00  0.887762          True          0.95             5   
8   0.887850       12.05  0.887762          True          0.95             5   
9   0.887850       12.10  0.887762          True          0.95             5   
10  0.887850       12.30  0.887762          True          0.95             5   
2   0.878505       10.00  0.878462          True          0.95             5   
3   0.878505       11.50  0.878462          True          0.95             5   
11  0.878505       12.40  0.878335          True          0.95             5   

   vect__ngram_range  
4             (1, 3)  
5             (1, 3)  
6             (1, 3)  
7             (1, 3)  
8             (1, 3)  
9             (1, 3)  
10            (1, 3)  
2             (1, 3)  
3             (1, 3)  
11            (1, 3)

In [55]:
filename = 'subjclueslen1-HLTEMNLP05.tff'
f = open(filename)
lines = f.readlines()
f.close()

In [56]:
words = []
for line in lines:
    sline = line.split()
    dline = dict([token.split('=') for token in sline if '=' in token])
    word = dline['word1']
    pol = dline['priorpolarity']
    if pol not in {'both', 'neutral'}:
        if pol in {'negative', 'weakneg'}:
            pol = 'NEG'
        else:
            pol = 'POS'
        words.append((word, pol))

word_dict = dict(words)

In [58]:
tkn = CountVectorizer().build_tokenizer()
def my_tkn(s):
    tokens = tkn(s)
    return [word_dict.get(token, token) for token in tokens]

In [59]:
vect = CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)
vect.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function my_tkn at 0x7f0c605b5950>,
                vocabulary=['POS', 'NEG'])

In [60]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [67]:
from sklearn.pipeline import FeatureUnion
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from util import print_eval

pipeline = Pipeline([
    ('vect', FeatureUnion([
        ('bow', CountVectorizer(       
        binary=True,
        min_df=5,
        max_df=0.95,
        ngram_range=(1, 3),)),
        ('pol', 
             Pipeline([
                ('pol', CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)),
                ('scl', StandardScaler(with_mean=False)),
            ])
        )
    ])),
    ('clf', MultinomialNB(alpha=12.0,fit_prior=True)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.88

              precision    recall  f1-score   support

         neg       0.92      0.83      0.87        54
         pos       0.84      0.92      0.88        53

    accuracy                           0.88       107
   macro avg       0.88      0.88      0.88       107
weighted avg       0.88      0.88      0.88       107

[[45  9]
 [ 4 49]]


In [64]:
y_pred = pipeline.predict(X_test)

In [65]:
save_results('my_classifierMNBtknHiper.csv', y_pred)