# Trabajo Práctico 2: Ejemplo

https://www.kaggle.com/c/intropln-analisis-de-sentimiento

## 1. Cargar Datos

In [316]:
from lab2 import *
train, dev, X_test = load_datasets_unlabeled_test()

In [317]:
X_train, y_train = train
X_dev, y_dev = dev
len(X_train), len(X_dev), len(X_test)

(963, 107, 500)

## 2. Entrenar

In [319]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC, SVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from tagging.fasttext2 import FasttextDictVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from util import print_short_eval
from sklearn.feature_extraction.text import TfidfVectorizer



#probando distintos clasificadores
clfs = [
    KNeighborsClassifier(),
    MultinomialNB(),
    DecisionTreeClassifier(random_state=0),
    LogisticRegression(random_state=0),
    LinearSVC(random_state=0),
    SVC(random_state=0),
    RandomForestClassifier(random_state=0),
]

#probar vectorizadores
vect = TfidfVectorizer(binary=True) #solo mejora el logistic regression
#vect = CountVectorizer(binary=True)

for clf in clfs:
    print(str(clf.__class__))
    pipeline = Pipeline([
        ('vect', vect),
        ('clf', clf),
    ])
    pipeline.fit(X_train, y_train)
    print_short_eval(pipeline, X_train, y_train)
    print_short_eval(pipeline, X_dev, y_dev)

<class 'sklearn.neighbors.classification.KNeighborsClassifier'>
accuracy	0.86	macro f1	0.86
accuracy	0.83	macro f1	0.83
<class 'sklearn.naive_bayes.MultinomialNB'>
accuracy	0.99	macro f1	0.99
accuracy	0.84	macro f1	0.84
<class 'sklearn.tree.tree.DecisionTreeClassifier'>
accuracy	1.00	macro f1	1.00
accuracy	0.70	macro f1	0.70
<class 'sklearn.linear_model.logistic.LogisticRegression'>


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


accuracy	0.99	macro f1	0.99
accuracy	0.88	macro f1	0.88
<class 'sklearn.svm.classes.LinearSVC'>
accuracy	1.00	macro f1	1.00
accuracy	0.87	macro f1	0.87
<class 'sklearn.svm.classes.SVC'>


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


accuracy	0.50	macro f1	0.33
accuracy	0.50	macro f1	0.33
<class 'sklearn.ensemble.forest.RandomForestClassifier'>


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


accuracy	0.99	macro f1	0.99
accuracy	0.75	macro f1	0.74


busqueda de parametros a analizar

In [128]:
#ngramas
pipeline = Pipeline([
    ('vect', CountVectorizer(
        binary=True,
        ngram_range=(1, 2),
    )),
    ('clf', LogisticRegression(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


accuracy	0.87

              precision    recall  f1-score   support

         neg       0.84      0.91      0.88        54
         pos       0.90      0.83      0.86        53

    accuracy                           0.87       107
   macro avg       0.87      0.87      0.87       107
weighted avg       0.87      0.87      0.87       107

[[49  5]
 [ 9 44]]


In [130]:
#min freq
pipeline = Pipeline([
    ('vect', CountVectorizer(
        binary=True,
        #min_df=5,
    )),
    ('clf', LogisticRegression(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.87

              precision    recall  f1-score   support

         neg       0.86      0.89      0.87        54
         pos       0.88      0.85      0.87        53

    accuracy                           0.87       107
   macro avg       0.87      0.87      0.87       107
weighted avg       0.87      0.87      0.87       107

[[48  6]
 [ 8 45]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [132]:
#max freq
pipeline = Pipeline([
    ('vect', CountVectorizer(
        binary=True,
        max_df=0.7,
    )),
    ('clf', LogisticRegression(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.86

              precision    recall  f1-score   support

         neg       0.87      0.85      0.86        54
         pos       0.85      0.87      0.86        53

    accuracy                           0.86       107
   macro avg       0.86      0.86      0.86       107
weighted avg       0.86      0.86      0.86       107

[[46  8]
 [ 7 46]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [133]:
#Stop Words
pipeline = Pipeline([
    ('vect', CountVectorizer(
        binary=True,
        stop_words='english',
    )),
    ('clf', LogisticRegression(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.84

              precision    recall  f1-score   support

         neg       0.84      0.85      0.84        54
         pos       0.85      0.83      0.84        53

    accuracy                           0.84       107
   macro avg       0.84      0.84      0.84       107
weighted avg       0.84      0.84      0.84       107

[[46  8]
 [ 9 44]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [183]:
#grid search
from sklearn.model_selection import ParameterGrid

param_grid = {
    'vect__binary': [True],
    #'vect__ngram_range': [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5)],
    #'vect__min_df': [1, 3, 5, 7],
    #'vect__max_df': [0.95, 0.9, 0.7],
    #segunda vuelta
    'vect__ngram_range': [(1, 3), (1, 4), (1, 5)],
    'vect__min_df': [ 5],
    'vect__max_df': [0.95, 0.96, 0.99, 0.97, 0.98],

    #mismos resultados
    'clf__random_state': [0],
}

params_list = list(ParameterGrid(param_grid))

In [184]:
params_list[10]
len(params_list)

15

In [185]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn import metrics
from util import eval

pipeline = Pipeline([
    ('vect', CountVectorizer()),
    ('clf', LogisticRegression()),
])

results = []
for params in params_list:
    # TODO: add progress bar!
    pipeline.set_params(**params)
    pipeline.fit(X_train, y_train)
    result = eval(pipeline, X_dev, y_dev)
    
    results.append({
        **result,
        **params,
    })

/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Defau

In [182]:
import pandas as pd

results_df = pd.DataFrame(results)
results_df.sort_values(['acc', 'f1'], ascending=False)[:10]

acc  clf__C  clf__random_state        f1  vect__binary  vect__max_df  \
0  0.906542     1.0                  0  0.906338          True          0.95   
1  0.906542     1.1                  0  0.906338          True          0.95   
2  0.906542     0.9                  0  0.906338          True          0.95   
3  0.897196     0.8                  0  0.896872          True          0.95   

   vect__min_df vect__ngram_range  
0             5            (1, 3)  
1             5            (1, 3)  
2             5            (1, 3)  
3             5            (1, 3)

grid search2, en clf ahora, distintas pruebas


In [220]:
from sklearn.model_selection import ParameterGrid

param_grid = {
    'vect__binary': [True],
    'vect__ngram_range': [(1, 3)],
    'vect__min_df': [5],
    'vect__max_df': [0.95],

    'clf__random_state': [0],
    #'clf__penalty': ["l1", "l2", "elasticnet", "none"],
    'clf__C': [1.0,1.1,0.9,0.8],
    'clf__solver': ["newton-cg", "lbfgs", "liblinear", "sag", "saga"],
    
    #'clf__solver': ["saga"],
    #'clf__l1_ratio': [0.5,0.8,0.2],
    

}

params_list = list(ParameterGrid(param_grid))

In [221]:
params_list[3]
len(params_list)

20

In [222]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn import metrics
from util import eval

pipeline = Pipeline([
    ('vect', CountVectorizer()),
    ('clf', LogisticRegression()),
])

results = []
for params in params_list:
    # TODO: add progress bar!
    pipeline.set_params(**params)
    pipeline.fit(X_train, y_train)
    result = eval(pipeline, X_dev, y_dev)
    
    results.append({
        **result,
        **params,
    })

/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/sag.py:337: C

In [223]:
import pandas as pd

results_df = pd.DataFrame(results)
results_df.sort_values(['acc', 'f1'], ascending=False)[:10]

acc  clf__C  clf__random_state clf__solver        f1  vect__binary  \
2   0.906542     1.0                  0   liblinear  0.906338          True   
7   0.906542     1.1                  0   liblinear  0.906338          True   
12  0.906542     0.9                  0   liblinear  0.906338          True   
15  0.906542     0.8                  0   newton-cg  0.906338          True   
16  0.906542     0.8                  0       lbfgs  0.906338          True   
0   0.897196     1.0                  0   newton-cg  0.897052          True   
1   0.897196     1.0                  0       lbfgs  0.897052          True   
5   0.897196     1.1                  0   newton-cg  0.897052          True   
6   0.897196     1.1                  0       lbfgs  0.897052          True   
10  0.897196     0.9                  0   newton-cg  0.897052          True   

    vect__max_df  vect__min_df vect__ngram_range  
2           0.95             5            (1, 3)  
7           0.95             5            (1, 3)  
12          0.95             5            (1, 3)  
15          0.95             5            (1, 3)  
16          0.95             5            (1, 3)  
0           0.95             5            (1, 3)  
1           0.95             5            (1, 3)  
5           0.95             5            (1, 3)  
6           0.95             5            (1, 3)  
10          0.95             5            (1, 3)

Pero ninguna de estas ultimas mejora lo anterior

Vamos a entrenar con los mejores

In [279]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from util import print_eval

pipeline = Pipeline([
    ('vect', CountVectorizer(
        binary=True,
        min_df=5,
        max_df=0.95,
        ngram_range=(1, 3),
        #stop_words='english',
    )),
    ('clf', LogisticRegression(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.91

              precision    recall  f1-score   support

         neg       0.88      0.94      0.91        54
         pos       0.94      0.87      0.90        53

    accuracy                           0.91       107
   macro avg       0.91      0.91      0.91       107
weighted avg       0.91      0.91      0.91       107

[[51  3]
 [ 7 46]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [260]:
pipeline.steps

[('vect', CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                  dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                  lowercase=True, max_df=0.95, max_features=None, min_df=5,
                  ngram_range=(1, 3), preprocessor=None, stop_words=None,
                  strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                  tokenizer=None, vocabulary=None)),
 ('clf',
  LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                     intercept_scaling=1, l1_ratio=None, max_iter=100,
                     multi_class='warn', n_jobs=None, penalty='l2',
                     random_state=0, solver='warn', tol=0.0001, verbose=0,
                     warm_start=False))]

In [261]:
vect = pipeline.named_steps['vect']
clf = pipeline.named_steps['clf']

In [262]:
features = vect.get_feature_names()
len(features)
features[:10]

['000', '10', '10 minutes', '100', '11', '12', '13', '14', '15', '15 minutes']

In [263]:
# clf?
coef = clf.coef_
coef.shape

(1, 8761)

In [264]:
import pandas as pd
features_df = pd.DataFrame({'name': features, 'coef': coef.ravel()})
features_df.sort_values('coef', inplace=True)

Veamos los mas relevantes

In [265]:
features_df[:10]

coef          name
5161 -0.754050            or
1794 -0.677734  disappointed
8591 -0.643693         worst
5429 -0.616644          poor
797  -0.603270           bad
130  -0.591270      actually
8027 -0.587674       version
6559 -0.574593      terrible
4483 -0.516134         money
8212 -0.513284         waste

In [230]:
features_df[-10:]

coef       name
2186  0.415454  excellent
4648  0.416817       must
2289  0.427388  fantastic
8458  0.430645       will
399   0.453981     and it
322   0.463035        and
3117  0.478712        his
4847  0.500057        now
2806  0.530864      great
8299  0.565419       well

In [237]:
pipeline.set_params(vect__stop_words='english')
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.85

              precision    recall  f1-score   support

         neg       0.84      0.87      0.85        54
         pos       0.86      0.83      0.85        53

    accuracy                           0.85       107
   macro avg       0.85      0.85      0.85       107
weighted avg       0.85      0.85      0.85       107

[[47  7]
 [ 9 44]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [239]:
vect = pipeline.named_steps['vect']
vect.get_stop_words()

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides'

In [254]:

def coef_df(pipeline):
    vect = pipeline.named_steps['vect']
    clf = pipeline.named_steps['clf']
    features = vect.get_feature_names()
    coef = clf.coef_
    coef_df = pd.DataFrame({'name': features, 'coef': coef.ravel()})
    coef_df.sort_values('coef', inplace=True)
    return coef_df


In [256]:
df = coef_df(pipeline)

In [257]:
df[:10]

coef          name
3488 -1.114752         worst
850  -1.069777  disappointed
3121 -1.013704      terrible
248  -0.984673           bad
2377 -0.959892          poor
3329 -0.932650       version
2059 -0.853315         money
3396 -0.843317         waste
1418 -0.796223          half
1521 -0.763020      horrible

In [258]:
df[-10:]

coef       name
239   0.656203    awesome
750   0.668358        day
2765  0.683552     seeing
1912  0.696769      loves
1830  0.698332      liked
2046  0.725265       miss
1215  0.730497    finally
1906  0.832377      loved
1063  0.995220  excellent
1132  1.003946  fantastic

Analizar errores

In [266]:
errors = []
for x, y1, y2 in zip(X_dev, y_dev, y_pred):
    if y1 != y2:
        errors.append({
            'item': x,
            'true': y1,
            'pred': y2})

errdf = pd.DataFrame(errors)
errdf['len'] = errdf['item'].apply(lambda x: len(x))

In [272]:
errdf

item  pred  true   len
0   b"In this dvd you have , the Boston POPS orche...     0     1   640
1   b"I 'll admit that I 've never seen films by M...     0     1  2521
2   b"I decided to buy this product new to avoid s...     1     0   606
3   b"Gran Torino is one of the best movies I have...     0     1   354
4   b"You really take your life in your hands ever...     0     1  5493
..                                                ...   ...   ...   ...
56  b"I was terribly excited to discover that one ...     0     1  2294
57  b"OK , I read the book back in middle school a...     1     0  1692
58  b'Ghost World is a coming-of-age story that de...     0     1   847
59  b"My 2 yr old has n't learned much out of it b...     0     1   160
60  b"As a former Marine and Vietnam veteran , I h...     0     1  1283

[61 rows x 4 columns]

In [273]:
y_prob = pipeline.predict_proba(X_dev)

In [274]:
errors = []
for i, (x, y1, y2, y2p) in enumerate(zip(X_dev, y_dev, y_pred, y_prob)):
    if y1 != y2:
        diff = y2p[y1] - y2p[y2]
        errors.append({
            'index': i,
            'item': x,
            'true': y1,
            'pred': y2,
            'pneg': y2p[0],
            'ppos': y2p[1],
            'diff': diff})

errdf = pd.DataFrame(errors)
errdf.sort_values('diff', inplace=True)

In [275]:
errdf[:10]

diff  index                                               item  \
60 -0.978398    106  b"As a former Marine and Vietnam veteran , I h...   
7  -0.336009     18  b'The video takes you through the making of th...   
35 -0.277311     69  b"This movie is excellent and deserves five st...   
45 -0.274102     85  b'I got this video with the understanding that...   
25 -0.176902     52  b'I watch a lot of documentaries on health , f...   
34  0.078200     66  b"I was really looking forward to Disney 's an...   
28  0.088744     57  b"There are certain movies in Hollywood where ...   
41  0.096540     80  b"we 've all seen the movie and we all know co...   
54  0.262532     98  b'This dvd was nothing like the novel , charac...   
27  0.313968     56  b"I watched Megaforce last night and there is ...   

        pneg      ppos  pred  true  
60  0.989199  0.010801     0     1  
7   0.668004  0.331996     0     1  
35  0.361345  0.638655     1     0  
45  0.362949  0.637051     1     0  
25  0.588451  0.411549     0     1  
34  0.539100  0.460900     1     0  
28  0.544372  0.455628     1     0  
41  0.451730  0.548270     0     1  
54  0.631266  0.368734     1     0  
27  0.656984  0.343016     1     0

In [276]:
x = X_dev[106]
print(x.decode('utf-8'))
#[s for s in x.decode('utf-8').split('\n') if 'movie' in s]

As a former Marine and Vietnam veteran , I have to disagree with Mr. Brennan 's portrayal of the second half of this film . The war scenes were marginal at best and failed to capture the `` realism '' of war ... Platoon was much better in that respect . Primarily because Oliver Stone was a veteran , himself . However the boot camp scenes in FMJ were dead on accurate . R.Lee Ermey played the Drill Instructor to perfection , as he should have , having been the very same in real life . I had several D.I . 's like this in boot camp and I can assure you , it WAS this way during the Vietnam war . I can laugh at the movie now , but while in boot camp it was no laughing matter , we were there to learn to fight and go to war , other skills were learned , but they were secondary . We had to be tough and they made sure we were . The boot camp portion was almost like a documentary to me ! Having said all that , the movie was like two parts to me.The first half and the second half . With one being 

In [278]:
filename = 'subjclueslen1-HLTEMNLP05.tff'
f = open(filename)
lines = f.readlines()
f.close()

In [280]:
words = []
for line in lines:
    sline = line.split()
    dline = dict([token.split('=') for token in sline if '=' in token])
    word = dline['word1']
    pol = dline['priorpolarity']
    if pol not in {'both', 'neutral'}:
        if pol in {'negative', 'weakneg'}:
            pol = 'NEG'
        else:
            pol = 'POS'
        words.append((word, pol))

word_dict = dict(words)

In [281]:
word_dict['abandon']

'NEG'

In [282]:
tkn = CountVectorizer().build_tokenizer()
def my_tkn(s):
    tokens = tkn(s)
    return [word_dict.get(token, token) for token in tokens]

In [283]:
my_tkn('creaky bastard')
#print(X_dev[0].decode('utf-8')[:200])
#my_tkn(X_dev[0].decode('utf-8'))

['creaky', 'NEG']

In [284]:
vect = CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)
vect.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function my_tkn at 0x7fca03627d90>,
                vocabulary=['POS', 'NEG'])

In [285]:
vect.transform(X_train[:10]).toarray()
#vect.get_feature_names()

array([[ 6,  3],
       [36, 23],
       [44,  9],
       [16, 12],
       [ 3,  1],
       [ 3,  0],
       [12,  6],
       [10,  7],
       [ 9,  7],
       [16, 13]])

In [286]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
vect = Pipeline([
    ('pol', CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)),
    ('scl', StandardScaler(with_mean=False)),
])
vect.fit(X_train)

Pipeline(memory=None,
         steps=[('pol',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function my_tkn at 0x7fca03627d90>,
                                 vocabulary=['POS', 'NEG'])),
                ('scl',
                 StandardScaler(copy=True, with_mean=False, with_std=True))],
         verbose=False)

In [287]:
vect.transform(X_train[:10]).toarray()

array([[0.41866372, 0.3010523 ],
       [2.51198234, 2.30806762],
       [3.07020064, 0.90315689],
       [1.1164366 , 1.20420919],
       [0.20933186, 0.10035077],
       [0.20933186, 0.        ],
       [0.83732745, 0.6021046 ],
       [0.69777287, 0.70245536],
       [0.62799559, 0.70245536],
       [1.1164366 , 1.30455996]])

In [288]:
from sklearn.pipeline import FeatureUnion
vect = FeatureUnion([
    ('bow', CountVectorizer(binary=True)),
    ('pol', 
         Pipeline([
            ('pol', CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)),
            ('scl', StandardScaler(with_mean=False)),
        ])
    )
])
vect.fit(X_train)

FeatureUnion(n_jobs=None,
             transformer_list=[('bow',
                                CountVectorizer(analyzer='word', binary=True,
                                                decode_error='strict',
                                                dtype=<class 'numpy.int64'>,
                                                encoding='utf-8',
                                                input='content', lowercase=True,
                                                max_df=1.0, max_features=None,
                                                min_df=1, ngram_range=(1, 1),
                                                preprocessor=None,
                                                stop_words=None,
                                                strip_accents=None,
                                                token_pattern='(?u)\\b\\w\\w+\\b',
                                                tokenizer=None,
                                                v...
     

In [289]:
vect.transform(X_train[:1])

<1x16114 sparse matrix of type '<class 'numpy.float64'>'
	with 55 stored elements in Compressed Sparse Row format>

In [290]:
from sklearn.pipeline import FeatureUnion
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from util import print_eval

pipeline = Pipeline([
    ('vect', FeatureUnion([
        ('bow', CountVectorizer(binary=True)),
        ('pol', 
             Pipeline([
                ('pol', CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)),
                ('scl', StandardScaler(with_mean=False)),
            ])
        )
    ])),
    ('clf', LogisticRegression(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.83

              precision    recall  f1-score   support

         neg       0.82      0.85      0.84        54
         pos       0.84      0.81      0.83        53

    accuracy                           0.83       107
   macro avg       0.83      0.83      0.83       107
weighted avg       0.83      0.83      0.83       107

[[46  8]
 [10 43]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [296]:
from sklearn.pipeline import FeatureUnion
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from util import print_eval
from sklearn.linear_model import LogisticRegressionCV


pipeline = Pipeline([
    ('vect', FeatureUnion([
        ('bow', CountVectorizer(
            binary=True,
            min_df=5,
            max_df=0.95,
            ngram_range=(1, 3),
        )),
        ('pol', 
             Pipeline([
                ('pol', CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)),
                ('scl', StandardScaler(with_mean=False)),
            ])
        )
    ])),
    ('clf', LogisticRegressionCV(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


accuracy	0.87

              precision    recall  f1-score   support

         neg       0.84      0.91      0.88        54
         pos       0.90      0.83      0.86        53

    accuracy                           0.87       107
   macro avg       0.87      0.87      0.87       107
weighted avg       0.87      0.87      0.87       107

[[49  5]
 [ 9 44]]


In [297]:
clf = pipeline.named_steps['clf']
clf.C_

array([0.35938137])

In [302]:
from sklearn.feature_extraction.text import TfidfVectorizer


pipeline = Pipeline([
    ('vect', FeatureUnion([
        ('bow', TfidfVectorizer(binary=True)),
        ('pol', 
             Pipeline([
                ('pol', CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)),
                ('scl', StandardScaler(with_mean=False)),
            ])
        )
    ])),
    ('clf', LogisticRegressionCV(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


accuracy	0.82

              precision    recall  f1-score   support

         neg       0.82      0.83      0.83        54
         pos       0.83      0.81      0.82        53

    accuracy                           0.82       107
   macro avg       0.82      0.82      0.82       107
weighted avg       0.82      0.82      0.82       107

[[45  9]
 [10 43]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [303]:
clf = pipeline.named_steps['clf']
clf.C_


array([10000.])

In [315]:

pipeline = Pipeline([
    ('vect', FeatureUnion([
        ('bow', CountVectorizer(
            binary=True,
            min_df=5,
            max_df=0.95,
            ngram_range=(1, 3),
        )),
        ('pol', 
             Pipeline([
                ('pol', CountVectorizer(vocabulary=['POS', 'NEG'], tokenizer=my_tkn)),
                ('scl', StandardScaler(with_mean=False)),
            ])
        )
    ])),
    ('clf', LogisticRegressionCV(random_state=0)),
])
pipeline.fit(X_train, y_train)
print_eval(pipeline, X_dev, y_dev)

accuracy	0.86

              precision    recall  f1-score   support

         neg       0.84      0.89      0.86        54
         pos       0.88      0.83      0.85        53

    accuracy                           0.86       107
   macro avg       0.86      0.86      0.86       107
weighted avg       0.86      0.86      0.86       107

[[48  6]
 [ 9 44]]


/home/daniel/.virtualenvs/pln/lib/python3.5/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


## 3. Testear y Generar Submission

In [308]:
y_pred = pipeline.predict(X_test)

In [309]:
save_results('my_classifierconlexiconyotros.csv', y_pred)